// ── SparkPro Field service worker ────────────────────────────────────────────
// Techs work in basements, crawlspaces, mechanical rooms and on rooftops. Losing
// signal must not mean losing the app. This caches the shell and static assets
// so a cold open works offline, while deliberately never caching Supabase —
// auth and tester data have to be live, and a stale cached session would be
// worse than an honest failure.

// Both values are rewritten at build time by scripts/inject-precache.mjs.
// Written so this file is still VALID JAVASCRIPT unprocessed: self.__PRECACHE__
// is simply undefined then, so PRECACHE falls back to [] and the worker
// degrades to the old lazy-caching behaviour instead of throwing on load. A
// service worker that throws at parse time registers nothing and fails silently.
const CACHE    = 'sparkpro-field-v7AboMJtDT_7c'
const PRECACHE = [
  "/sparkpro-field-live/",
  "/sparkpro-field-live/index.html",
  "/sparkpro-field-live/manifest.json",
  "/sparkpro-field-live/assets/field-splash-DyWzWNQ-.webp",
  "/sparkpro-field-live/assets/field-splash-mobile-7npyWWET.webp",
  "/sparkpro-field-live/assets/hex-bg-BH7n1x9W.webp",
  "/sparkpro-field-live/assets/index-B8NwM4rG.css",
  "/sparkpro-field-live/assets/index-CEeLXEmF.js",
  "/sparkpro-field-live/assets/sp-Bp1IW3QM.webp",
  "/sparkpro-field-live/assets/sparkpro-bg-DHVfRdv9.webp",
  "/sparkpro-field-live/assets/sparkpro-wordmark-S-wq63Au.png",
  "/sparkpro-field-live/voice/core/0034g4o-6.opus",
  "/sparkpro-field-live/voice/core/008md30-1f.opus",
  "/sparkpro-field-live/voice/core/00dxd18-n.opus",
  "/sparkpro-field-live/voice/core/00eaxal-n.opus",
  "/sparkpro-field-live/voice/core/00ev5e8-g.opus",
  "/sparkpro-field-live/voice/core/00fm177-c.opus",
  "/sparkpro-field-live/voice/core/00g0ioc-b.opus",
  "/sparkpro-field-live/voice/core/00gfom9-8.opus",
  "/sparkpro-field-live/voice/core/00hmarn-1u.opus",
  "/sparkpro-field-live/voice/core/00l7c5y-f.opus",
  "/sparkpro-field-live/voice/core/00obp5m-1c.opus",
  "/sparkpro-field-live/voice/core/00pztd9-9.opus",
  "/sparkpro-field-live/voice/core/00txf04-5.opus",
  "/sparkpro-field-live/voice/core/00xu8b9-1e.opus",
  "/sparkpro-field-live/voice/core/00ym2l5-2q.opus",
  "/sparkpro-field-live/voice/core/013y6mf-1f.opus",
  "/sparkpro-field-live/voice/core/01eebyd-c.opus",
  "/sparkpro-field-live/voice/core/01orlh2-l.opus",
  "/sparkpro-field-live/voice/core/01yl8bc-h.opus",
  "/sparkpro-field-live/voice/core/024yoew-20.opus",
  "/sparkpro-field-live/voice/core/025vhqq-a.opus",
  "/sparkpro-field-live/voice/core/025vy22-7.opus",
  "/sparkpro-field-live/voice/core/02b9emv-i.opus",
  "/sparkpro-field-live/voice/core/02ejsf2-b.opus",
  "/sparkpro-field-live/voice/core/02h08xu-1e.opus",
  "/sparkpro-field-live/voice/core/02jqnqx-d.opus",
  "/sparkpro-field-live/voice/core/02zbe50-c.opus",
  "/sparkpro-field-live/voice/core/038d4l9-a.opus",
  "/sparkpro-field-live/voice/core/03gtds5-h.opus",
  "/sparkpro-field-live/voice/core/03k3yu1-9.opus",
  "/sparkpro-field-live/voice/core/03krlci-h.opus",
  "/sparkpro-field-live/voice/core/03lqgvl-b.opus",
  "/sparkpro-field-live/voice/core/03pihai-w.opus",
  "/sparkpro-field-live/voice/core/03v7ohq-b.opus",
  "/sparkpro-field-live/voice/core/03wkad8-a.opus",
  "/sparkpro-field-live/voice/core/03x1f7p-1a.opus",
  "/sparkpro-field-live/voice/core/042hudl-9.opus",
  "/sparkpro-field-live/voice/core/047axro-h.opus",
  "/sparkpro-field-live/voice/core/047gkh2-3.opus",
  "/sparkpro-field-live/voice/core/04mhh9j-1i.opus",
  "/sparkpro-field-live/voice/core/050j99j-7.opus",
  "/sparkpro-field-live/voice/core/0531vtx-k.opus",
  "/sparkpro-field-live/voice/core/05abir3-h.opus",
  "/sparkpro-field-live/voice/core/05d4hxv-l.opus",
  "/sparkpro-field-live/voice/core/05fydex-a.opus",
  "/sparkpro-field-live/voice/core/05gmjxp-1f.opus",
  "/sparkpro-field-live/voice/core/05h1h17-m.opus",
  "/sparkpro-field-live/voice/core/05jia5u-g.opus",
  "/sparkpro-field-live/voice/core/05lxnw2-2i.opus",
  "/sparkpro-field-live/voice/core/05tv1zv-2r.opus",
  "/sparkpro-field-live/voice/core/05w4doh-h.opus",
  "/sparkpro-field-live/voice/core/062xs9p-9.opus",
  "/sparkpro-field-live/voice/core/06591zp-4.opus",
  "/sparkpro-field-live/voice/core/067nly7-1r.opus",
  "/sparkpro-field-live/voice/core/06bgg7l-1i.opus",
  "/sparkpro-field-live/voice/core/06i2an5-9.opus",
  "/sparkpro-field-live/voice/core/06kjoh3-1u.opus",
  "/sparkpro-field-live/voice/core/06qg4c1-20.opus",
  "/sparkpro-field-live/voice/core/06vvgm3-g.opus",
  "/sparkpro-field-live/voice/core/07djbjp-6.opus",
  "/sparkpro-field-live/voice/core/07pcfjw-d.opus",
  "/sparkpro-field-live/voice/core/081p0xo-g.opus",
  "/sparkpro-field-live/voice/core/088zqbp-2j.opus",
  "/sparkpro-field-live/voice/core/08cawt5-1w.opus",
  "/sparkpro-field-live/voice/core/08ds35k-2s.opus",
  "/sparkpro-field-live/voice/core/08lcsyr-16.opus",
  "/sparkpro-field-live/voice/core/08njxab-19.opus",
  "/sparkpro-field-live/voice/core/08ty8we-e.opus",
  "/sparkpro-field-live/voice/core/08xwbvx-2r.opus",
  "/sparkpro-field-live/voice/core/09275s1-23.opus",
  "/sparkpro-field-live/voice/core/096rhzs-l.opus",
  "/sparkpro-field-live/voice/core/098l2wz-38.opus",
  "/sparkpro-field-live/voice/core/09baacj-6.opus",
  "/sparkpro-field-live/voice/core/09pho4l-h.opus",
  "/sparkpro-field-live/voice/core/09supgz-9.opus",
  "/sparkpro-field-live/voice/core/0a0qc02-5.opus",
  "/sparkpro-field-live/voice/core/0a20dmn-h.opus",
  "/sparkpro-field-live/voice/core/0a20pbg-a.opus",
  "/sparkpro-field-live/voice/core/0a5jb7f-c.opus",
  "/sparkpro-field-live/voice/core/0aazrho-b.opus",
  "/sparkpro-field-live/voice/core/0ah5ag7-i.opus",
  "/sparkpro-field-live/voice/core/0aho33x-d.opus",
  "/sparkpro-field-live/voice/core/0ajf2vq-k.opus",
  "/sparkpro-field-live/voice/core/0ak2u4o-9.opus",
  "/sparkpro-field-live/voice/core/0asz3av-a.opus",
  "/sparkpro-field-live/voice/core/0awjr4t-b.opus",
  "/sparkpro-field-live/voice/core/0ay5fxh-c.opus",
  "/sparkpro-field-live/voice/core/0b01rtl-1e.opus",
  "/sparkpro-field-live/voice/core/0b01vd6-9.opus",
  "/sparkpro-field-live/voice/core/0b3ryqt-g.opus",
  "/sparkpro-field-live/voice/core/0b49tu1-c.opus",
  "/sparkpro-field-live/voice/core/0b4nce0-b.opus",
  "/sparkpro-field-live/voice/core/0b6a5al-7.opus",
  "/sparkpro-field-live/voice/core/0b6t120-b.opus",
  "/sparkpro-field-live/voice/core/0bb1c7s-a.opus",
  "/sparkpro-field-live/voice/core/0bcgnge-3j.opus",
  "/sparkpro-field-live/voice/core/0bfdaxw-17.opus",
  "/sparkpro-field-live/voice/core/0bzvd2f-i.opus",
  "/sparkpro-field-live/voice/core/0c3xwi3-b.opus",
  "/sparkpro-field-live/voice/core/0c701nu-22.opus",
  "/sparkpro-field-live/voice/core/0cbap8f-c.opus",
  "/sparkpro-field-live/voice/core/0cdar8y-b.opus",
  "/sparkpro-field-live/voice/core/0chkoyh-1d.opus",
  "/sparkpro-field-live/voice/core/0cmuj7d-c.opus",
  "/sparkpro-field-live/voice/core/0d2le1h-h.opus",
  "/sparkpro-field-live/voice/core/0d3gltr-9.opus",
  "/sparkpro-field-live/voice/core/0d5lr51-4.opus",
  "/sparkpro-field-live/voice/core/0d5v9bb-a.opus",
  "/sparkpro-field-live/voice/core/0d64jjj-c.opus",
  "/sparkpro-field-live/voice/core/0d7mauc-d.opus",
  "/sparkpro-field-live/voice/core/0db3q0d-c.opus",
  "/sparkpro-field-live/voice/core/0de3do3-l.opus",
  "/sparkpro-field-live/voice/core/0dx4pz4-f.opus",
  "/sparkpro-field-live/voice/core/0e0bbuf-a.opus",
  "/sparkpro-field-live/voice/core/0e0j2sb-15.opus",
  "/sparkpro-field-live/voice/core/0e2ogjb-1d.opus",
  "/sparkpro-field-live/voice/core/0e8yzc9-n.opus",
  "/sparkpro-field-live/voice/core/0ec4i94-c.opus",
  "/sparkpro-field-live/voice/core/0ecbenw-j.opus",
  "/sparkpro-field-live/voice/core/0eea6od-47.opus",
  "/sparkpro-field-live/voice/core/0eg2b7l-z.opus",
  "/sparkpro-field-live/voice/core/0ehxr87-1l.opus",
  "/sparkpro-field-live/voice/core/0ejw8t9-8.opus",
  "/sparkpro-field-live/voice/core/0eprczu-4.opus",
  "/sparkpro-field-live/voice/core/0eujfum-5.opus",
  "/sparkpro-field-live/voice/core/0eybtno-2q.opus",
  "/sparkpro-field-live/voice/core/0f5r6nk-b.opus",
  "/sparkpro-field-live/voice/core/0f6sujm-j.opus",
  "/sparkpro-field-live/voice/core/0f742oz-d.opus",
  "/sparkpro-field-live/voice/core/0f9oyr6-1v.opus",
  "/sparkpro-field-live/voice/core/0fc3fl5-14.opus",
  "/sparkpro-field-live/voice/core/0fl0vpo-f.opus",
  "/sparkpro-field-live/voice/core/0fp3mdk-h.opus",
  "/sparkpro-field-live/voice/core/0fpqan8-b.opus",
  "/sparkpro-field-live/voice/core/0fr5gwb-b.opus",
  "/sparkpro-field-live/voice/core/0fzs0nl-14.opus",
  "/sparkpro-field-live/voice/core/0g2argk-f.opus",
  "/sparkpro-field-live/voice/core/0gatges-2k.opus",
  "/sparkpro-field-live/voice/core/0gfynji-17.opus",
  "/sparkpro-field-live/voice/core/0gr00cr-d.opus",
  "/sparkpro-field-live/voice/core/0gw9qfg-b.opus",
  "/sparkpro-field-live/voice/core/0h0swhr-g.opus",
  "/sparkpro-field-live/voice/core/0h2xg0c-b.opus",
  "/sparkpro-field-live/voice/core/0h6zfpr-x.opus",
  "/sparkpro-field-live/voice/core/0h72q99-f.opus",
  "/sparkpro-field-live/voice/core/0h9wsem-n.opus",
  "/sparkpro-field-live/voice/core/0hbj45y-1i.opus",
  "/sparkpro-field-live/voice/core/0hcfy7p-a.opus",
  "/sparkpro-field-live/voice/core/0hfsigg-5.opus",
  "/sparkpro-field-live/voice/core/0hocjs7-s.opus",
  "/sparkpro-field-live/voice/core/0hprcw4-2j.opus",
  "/sparkpro-field-live/voice/core/0hv9oor-b.opus",
  "/sparkpro-field-live/voice/core/0i99mwm-z.opus",
  "/sparkpro-field-live/voice/core/0idyip0-2.opus",
  "/sparkpro-field-live/voice/core/0ijd3lj-d.opus",
  "/sparkpro-field-live/voice/core/0irq1v0-i.opus",
  "/sparkpro-field-live/voice/core/0j3jh6z-f.opus",
  "/sparkpro-field-live/voice/core/0j9b9ts-c.opus",
  "/sparkpro-field-live/voice/core/0jjzwho-f.opus",
  "/sparkpro-field-live/voice/core/0jo8jue-o.opus",
  "/sparkpro-field-live/voice/core/0jp0gq9-e.opus",
  "/sparkpro-field-live/voice/core/0jsk9k6-1h.opus",
  "/sparkpro-field-live/voice/core/0jtwtbv-u.opus",
  "/sparkpro-field-live/voice/core/0k495j5-5.opus",
  "/sparkpro-field-live/voice/core/0kfba9n-a.opus",
  "/sparkpro-field-live/voice/core/0kgwum5-b.opus",
  "/sparkpro-field-live/voice/core/0kkaj1r-c.opus",
  "/sparkpro-field-live/voice/core/0kvkq5t-6.opus",
  "/sparkpro-field-live/voice/core/0kx28ll-8.opus",
  "/sparkpro-field-live/voice/core/0l4pvt4-i.opus",
  "/sparkpro-field-live/voice/core/0l6jhmp-l.opus",
  "/sparkpro-field-live/voice/core/0lcqyka-1b.opus",
  "/sparkpro-field-live/voice/core/0libs9g-c.opus",
  "/sparkpro-field-live/voice/core/0ljqhsi-c.opus",
  "/sparkpro-field-live/voice/core/0lrjd6f-4.opus",
  "/sparkpro-field-live/voice/core/0ltbyq8-3.opus",
  "/sparkpro-field-live/voice/core/0luzjfp-h.opus",
  "/sparkpro-field-live/voice/core/0m0jnby-4.opus",
  "/sparkpro-field-live/voice/core/0m0rr57-6.opus",
  "/sparkpro-field-live/voice/core/0meg8eq-6.opus",
  "/sparkpro-field-live/voice/core/0mv6m84-2f.opus",
  "/sparkpro-field-live/voice/core/0mxe1cy-5.opus",
  "/sparkpro-field-live/voice/core/0n0akca-a.opus",
  "/sparkpro-field-live/voice/core/0n1j3a1-z.opus",
  "/sparkpro-field-live/voice/core/0n5bx17-7.opus",
  "/sparkpro-field-live/voice/core/0nec8mb-x.opus",
  "/sparkpro-field-live/voice/core/0ntlana-26.opus",
  "/sparkpro-field-live/voice/core/0nvuskg-1b.opus",
  "/sparkpro-field-live/voice/core/0o0csqj-a.opus",
  "/sparkpro-field-live/voice/core/0o9n9nk-f.opus",
  "/sparkpro-field-live/voice/core/0obk4vg-c.opus",
  "/sparkpro-field-live/voice/core/0ok2t7h-c.opus",
  "/sparkpro-field-live/voice/core/0olx9ns-h.opus",
  "/sparkpro-field-live/voice/core/0ot16o8-a.opus",
  "/sparkpro-field-live/voice/core/0otti2e-4f.opus",
  "/sparkpro-field-live/voice/core/0p3ex7j-a.opus",
  "/sparkpro-field-live/voice/core/0p70a26-o.opus",
  "/sparkpro-field-live/voice/core/0p7ccb8-f.opus",
  "/sparkpro-field-live/voice/core/0phkild-1k.opus",
  "/sparkpro-field-live/voice/core/0pigdyn-n.opus",
  "/sparkpro-field-live/voice/core/0pjjl8z-1e.opus",
  "/sparkpro-field-live/voice/core/0pq32lk-4.opus",
  "/sparkpro-field-live/voice/core/0prti00-17.opus",
  "/sparkpro-field-live/voice/core/0puzibo-2.opus",
  "/sparkpro-field-live/voice/core/0q21nkk-b.opus",
  "/sparkpro-field-live/voice/core/0q93bx3-e.opus",
  "/sparkpro-field-live/voice/core/0qg4lyw-a.opus",
  "/sparkpro-field-live/voice/core/0qiyhra-o.opus",
  "/sparkpro-field-live/voice/core/0qj3g83-j.opus",
  "/sparkpro-field-live/voice/core/0qmzimi-a.opus",
  "/sparkpro-field-live/voice/core/0qsk54f-b.opus",
  "/sparkpro-field-live/voice/core/0qsrbq1-b.opus",
  "/sparkpro-field-live/voice/core/0qv8tqk-3.opus",
  "/sparkpro-field-live/voice/core/0r0ub5z-j.opus",
  "/sparkpro-field-live/voice/core/0r5tc71-9.opus",
  "/sparkpro-field-live/voice/core/0r7jgzv-20.opus",
  "/sparkpro-field-live/voice/core/0r8umqk-5.opus",
  "/sparkpro-field-live/voice/core/0r90oai-2.opus",
  "/sparkpro-field-live/voice/core/0rj1gs6-8.opus",
  "/sparkpro-field-live/voice/core/0ruf013-c.opus",
  "/sparkpro-field-live/voice/core/0s69zj2-d.opus",
  "/sparkpro-field-live/voice/core/0s72c2p-2s.opus",
  "/sparkpro-field-live/voice/core/0s7nesf-k.opus",
  "/sparkpro-field-live/voice/core/0s9vgl9-q.opus",
  "/sparkpro-field-live/voice/core/0sbfb3o-5.opus",
  "/sparkpro-field-live/voice/core/0shzd2i-7.opus",
  "/sparkpro-field-live/voice/core/0sjo23s-c.opus",
  "/sparkpro-field-live/voice/core/0sm7uac-9.opus",
  "/sparkpro-field-live/voice/core/0smjsjm-1e.opus",
  "/sparkpro-field-live/voice/core/0sn3u93-7.opus",
  "/sparkpro-field-live/voice/core/0spl33r-a.opus",
  "/sparkpro-field-live/voice/core/0sq7kh4-e.opus",
  "/sparkpro-field-live/voice/core/0t4m62g-1f.opus",
  "/sparkpro-field-live/voice/core/0t8fn63-w.opus",
  "/sparkpro-field-live/voice/core/0tbeey1-1h.opus",
  "/sparkpro-field-live/voice/core/0tbvgiz-25.opus",
  "/sparkpro-field-live/voice/core/0tedkhs-a.opus",
  "/sparkpro-field-live/voice/core/0tejj26-5.opus",
  "/sparkpro-field-live/voice/core/0tgctjw-3p.opus",
  "/sparkpro-field-live/voice/core/0tjom7z-3k.opus",
  "/sparkpro-field-live/voice/core/0tll0ic-7.opus",
  "/sparkpro-field-live/voice/core/0tqompf-l.opus",
  "/sparkpro-field-live/voice/core/0u7qi3f-14.opus",
  "/sparkpro-field-live/voice/core/0u9d5xm-h.opus",
  "/sparkpro-field-live/voice/core/0u9pjjr-f.opus",
  "/sparkpro-field-live/voice/core/0ucxirc-b.opus",
  "/sparkpro-field-live/voice/core/0uqwzsg-b.opus",
  "/sparkpro-field-live/voice/core/0uzbo8d-d.opus",
  "/sparkpro-field-live/voice/core/0v0sq8d-s.opus",
  "/sparkpro-field-live/voice/core/0v13uc8-b.opus",
  "/sparkpro-field-live/voice/core/0v2suyl-2v.opus",
  "/sparkpro-field-live/voice/core/0v4vutt-d.opus",
  "/sparkpro-field-live/voice/core/0v5f0sh-e.opus",
  "/sparkpro-field-live/voice/core/0v5zi4c-1c.opus",
  "/sparkpro-field-live/voice/core/0vjgws8-1n.opus",
  "/sparkpro-field-live/voice/core/0vmru2y-b.opus",
  "/sparkpro-field-live/voice/core/0vrfdsq-f.opus",
  "/sparkpro-field-live/voice/core/0vzqt2a-a.opus",
  "/sparkpro-field-live/voice/core/0wm7azu-a.opus",
  "/sparkpro-field-live/voice/core/0wmc5pf-2f.opus",
  "/sparkpro-field-live/voice/core/0wqfmmy-7.opus",
  "/sparkpro-field-live/voice/core/0wuwm2n-b.opus",
  "/sparkpro-field-live/voice/core/0xaefeo-d.opus",
  "/sparkpro-field-live/voice/core/0xbx34r-u.opus",
  "/sparkpro-field-live/voice/core/0xcmiim-12.opus",
  "/sparkpro-field-live/voice/core/0xjidwl-5.opus",
  "/sparkpro-field-live/voice/core/0xnlk3o-s.opus",
  "/sparkpro-field-live/voice/core/0xqn41m-1g.opus",
  "/sparkpro-field-live/voice/core/0xri7vd-1k.opus",
  "/sparkpro-field-live/voice/core/0xv1luw-2b.opus",
  "/sparkpro-field-live/voice/core/0xxke3t-20.opus",
  "/sparkpro-field-live/voice/core/0xz96gx-1t.opus",
  "/sparkpro-field-live/voice/core/0y6dwzd-2c.opus",
  "/sparkpro-field-live/voice/core/0y95avt-e.opus",
  "/sparkpro-field-live/voice/core/0ynjnxd-6.opus",
  "/sparkpro-field-live/voice/core/0yxlc1p-2j.opus",
  "/sparkpro-field-live/voice/core/0z937y4-1o.opus",
  "/sparkpro-field-live/voice/core/0zjyvld-2q.opus",
  "/sparkpro-field-live/voice/core/0zloxpi-1x.opus",
  "/sparkpro-field-live/voice/core/0zqmu3x-c.opus",
  "/sparkpro-field-live/voice/core/0zui3lm-n.opus",
  "/sparkpro-field-live/voice/core/0zygu6c-e.opus",
  "/sparkpro-field-live/voice/core/100i3ty-1a.opus",
  "/sparkpro-field-live/voice/core/1010zs6-2b.opus",
  "/sparkpro-field-live/voice/core/106vake-8.opus",
  "/sparkpro-field-live/voice/core/106zvlu-8.opus",
  "/sparkpro-field-live/voice/core/109ssgs-1h.opus",
  "/sparkpro-field-live/voice/core/10anp2y-d.opus",
  "/sparkpro-field-live/voice/core/10gek0m-l.opus",
  "/sparkpro-field-live/voice/core/10lsnln-i.opus",
  "/sparkpro-field-live/voice/core/10mzdtn-a.opus",
  "/sparkpro-field-live/voice/core/10pxx0d-p.opus",
  "/sparkpro-field-live/voice/core/10urea0-h.opus",
  "/sparkpro-field-live/voice/core/10zaeip-38.opus",
  "/sparkpro-field-live/voice/core/111mb9r-5.opus",
  "/sparkpro-field-live/voice/core/112kcl6-1u.opus",
  "/sparkpro-field-live/voice/core/112oefe-b.opus",
  "/sparkpro-field-live/voice/core/1143lk8-17.opus",
  "/sparkpro-field-live/voice/core/1157vt5-d.opus",
  "/sparkpro-field-live/voice/core/117y3lx-b.opus",
  "/sparkpro-field-live/voice/core/11pop94-2s.opus",
  "/sparkpro-field-live/voice/core/11s3687-j.opus",
  "/sparkpro-field-live/voice/core/11vp0w3-5.opus",
  "/sparkpro-field-live/voice/core/129fe8m-h.opus",
  "/sparkpro-field-live/voice/core/12e843v-j.opus",
  "/sparkpro-field-live/voice/core/12ke9n7-e.opus",
  "/sparkpro-field-live/voice/core/12ksmod-z.opus",
  "/sparkpro-field-live/voice/core/12osqxv-4.opus",
  "/sparkpro-field-live/voice/core/12ru94o-n.opus",
  "/sparkpro-field-live/voice/core/12rx6wx-n.opus",
  "/sparkpro-field-live/voice/core/12s8hsl-9.opus",
  "/sparkpro-field-live/voice/core/12z44ed-1m.opus",
  "/sparkpro-field-live/voice/core/1380v8c-i.opus",
  "/sparkpro-field-live/voice/core/13gb5gf-2j.opus",
  "/sparkpro-field-live/voice/core/13kprdp-14.opus",
  "/sparkpro-field-live/voice/core/13o0790-9.opus",
  "/sparkpro-field-live/voice/core/13vps6g-c.opus",
  "/sparkpro-field-live/voice/core/13xydmo-6.opus",
  "/sparkpro-field-live/voice/core/13zojg8-l.opus",
  "/sparkpro-field-live/voice/core/144ohqi-6.opus",
  "/sparkpro-field-live/voice/core/146ue4f-f.opus",
  "/sparkpro-field-live/voice/core/147psq1-1g.opus",
  "/sparkpro-field-live/voice/core/1484gs4-b.opus",
  "/sparkpro-field-live/voice/core/14bgx51-7.opus",
  "/sparkpro-field-live/voice/core/14f3ufs-1b.opus",
  "/sparkpro-field-live/voice/core/14jrto3-19.opus",
  "/sparkpro-field-live/voice/core/14ris5o-k.opus",
  "/sparkpro-field-live/voice/core/14u5cjz-f.opus",
  "/sparkpro-field-live/voice/core/14v7035-d.opus",
  "/sparkpro-field-live/voice/core/150g73j-1d.opus",
  "/sparkpro-field-live/voice/core/151k2t8-i.opus",
  "/sparkpro-field-live/voice/core/154875g-e.opus",
  "/sparkpro-field-live/voice/core/155m8xj-8.opus",
  "/sparkpro-field-live/voice/core/15dv9kk-31.opus",
  "/sparkpro-field-live/voice/core/15eq9j6-7.opus",
  "/sparkpro-field-live/voice/core/15s9y2h-b.opus",
  "/sparkpro-field-live/voice/core/15tox1e-f.opus",
  "/sparkpro-field-live/voice/core/165vaej-2q.opus",
  "/sparkpro-field-live/voice/core/16dooez-l.opus",
  "/sparkpro-field-live/voice/core/16fhnqt-j.opus",
  "/sparkpro-field-live/voice/core/16ou5y7-o.opus",
  "/sparkpro-field-live/voice/core/16pvhw5-j.opus",
  "/sparkpro-field-live/voice/core/16royaz-h.opus",
  "/sparkpro-field-live/voice/core/16vyk8l-d.opus",
  "/sparkpro-field-live/voice/core/16xy1a0-j.opus",
  "/sparkpro-field-live/voice/core/174l62p-e.opus",
  "/sparkpro-field-live/voice/core/17apuaw-7.opus",
  "/sparkpro-field-live/voice/core/17m18cv-o.opus",
  "/sparkpro-field-live/voice/core/17tyqk2-17.opus",
  "/sparkpro-field-live/voice/core/18163vz-8.opus",
  "/sparkpro-field-live/voice/core/182umr6-c.opus",
  "/sparkpro-field-live/voice/core/187lly6-k.opus",
  "/sparkpro-field-live/voice/core/18aaydl-1f.opus",
  "/sparkpro-field-live/voice/core/18blh0d-p.opus",
  "/sparkpro-field-live/voice/core/18ir2at-26.opus",
  "/sparkpro-field-live/voice/core/18v5fk0-d.opus",
  "/sparkpro-field-live/voice/core/18xqhao-a.opus",
  "/sparkpro-field-live/voice/core/18zv8ys-a.opus",
  "/sparkpro-field-live/voice/core/1910zad-e.opus",
  "/sparkpro-field-live/voice/core/191phou-1g.opus",
  "/sparkpro-field-live/voice/core/192qsy9-j.opus",
  "/sparkpro-field-live/voice/core/195nhz8-f.opus",
  "/sparkpro-field-live/voice/core/19emtxn-a.opus",
  "/sparkpro-field-live/voice/core/19g79ou-9.opus",
  "/sparkpro-field-live/voice/core/19hyo5k-18.opus",
  "/sparkpro-field-live/voice/core/19kyjud-h.opus",
  "/sparkpro-field-live/voice/core/19pwxnq-9.opus",
  "/sparkpro-field-live/voice/core/19rfre7-7.opus",
  "/sparkpro-field-live/voice/core/19sbc68-16.opus",
  "/sparkpro-field-live/voice/core/19tc2y0-m.opus",
  "/sparkpro-field-live/voice/core/19x2uj4-8.opus",
  "/sparkpro-field-live/voice/core/19x98ls-l.opus",
  "/sparkpro-field-live/voice/core/19z2x4e-j.opus",
  "/sparkpro-field-live/voice/core/1a05z16-1k.opus",
  "/sparkpro-field-live/voice/core/1a0k1z4-i.opus",
  "/sparkpro-field-live/voice/core/1a5poty-n.opus",
  "/sparkpro-field-live/voice/core/1ajb8s4-2c.opus",
  "/sparkpro-field-live/voice/core/1alsa68-b.opus",
  "/sparkpro-field-live/voice/core/1aosl5s-i.opus",
  "/sparkpro-field-live/voice/core/1ap8xo8-r.opus",
  "/sparkpro-field-live/voice/core/1ar7q85-1d.opus",
  "/sparkpro-field-live/voice/core/1atfrpc-z.opus",
  "/sparkpro-field-live/voice/core/1b6fp1h-h.opus",
  "/sparkpro-field-live/voice/core/1b9v2z0-a.opus",
  "/sparkpro-field-live/voice/core/1bewqeo-c.opus",
  "/sparkpro-field-live/voice/core/1bgnc3x-g.opus",
  "/sparkpro-field-live/voice/core/1bk2rvd-2s.opus",
  "/sparkpro-field-live/voice/core/1bps3bx-6.opus",
  "/sparkpro-field-live/voice/core/1br9vwa-c.opus",
  "/sparkpro-field-live/voice/core/1btnnql-a.opus",
  "/sparkpro-field-live/voice/core/1bvtt0e-5.opus",
  "/sparkpro-field-live/voice/core/1byczbz-v.opus",
  "/sparkpro-field-live/voice/core/1c0kn2f-f.opus",
  "/sparkpro-field-live/voice/core/1c27o9h-a.opus",
  "/sparkpro-field-live/voice/core/1c3dvwq-c.opus",
  "/sparkpro-field-live/voice/core/1c7ex2m-7.opus",
  "/sparkpro-field-live/voice/core/1c8jaaa-c.opus",
  "/sparkpro-field-live/voice/core/1ccum3x-17.opus",
  "/sparkpro-field-live/voice/core/1ccuyj6-2m.opus",
  "/sparkpro-field-live/voice/core/1ch2k5x-4.opus",
  "/sparkpro-field-live/voice/core/1cl4hjt-h.opus",
  "/sparkpro-field-live/voice/core/1cnbawe-7.opus",
  "/sparkpro-field-live/voice/core/1cp4kfe-2n.opus",
  "/sparkpro-field-live/voice/core/1ctv48c-15.opus",
  "/sparkpro-field-live/voice/core/1cu3sr4-g.opus",
  "/sparkpro-field-live/voice/core/1czsblk-7.opus",
  "/sparkpro-field-live/voice/core/1d01z68-v.opus",
  "/sparkpro-field-live/voice/core/1d2w1fh-25.opus",
  "/sparkpro-field-live/voice/core/1d3mpo6-b.opus",
  "/sparkpro-field-live/voice/core/1dal6pc-d.opus",
  "/sparkpro-field-live/voice/core/1dbt27t-c.opus",
  "/sparkpro-field-live/voice/core/1diicyf-2j.opus",
  "/sparkpro-field-live/voice/core/1dlieq9-d.opus",
  "/sparkpro-field-live/voice/core/1dtpz1k-a.opus",
  "/sparkpro-field-live/voice/core/1dtrev9-m.opus",
  "/sparkpro-field-live/voice/core/1e11gvl-b.opus",
  "/sparkpro-field-live/voice/core/1eem7ta-5.opus",
  "/sparkpro-field-live/voice/core/1eqefnw-n.opus",
  "/sparkpro-field-live/voice/core/1f4fbwa-15.opus",
  "/sparkpro-field-live/voice/core/1f5xvo5-o.opus",
  "/sparkpro-field-live/voice/core/1fijvkb-1e.opus",
  "/sparkpro-field-live/voice/core/1fkd31o-8.opus",
  "/sparkpro-field-live/voice/core/1fnfegf-3.opus",
  "/sparkpro-field-live/voice/core/1forz5l-10.opus",
  "/sparkpro-field-live/voice/core/1fs03kc-j.opus",
  "/sparkpro-field-live/voice/core/1fs3pe1-4.opus",
  "/sparkpro-field-live/voice/core/1fxz7th-4.opus",
  "/sparkpro-field-live/voice/core/1fyjgrm-m.opus",
  "/sparkpro-field-live/voice/core/1g1lxxs-2q.opus",
  "/sparkpro-field-live/voice/core/1gd1k2k-j.opus",
  "/sparkpro-field-live/voice/core/1gdhhri-k.opus",
  "/sparkpro-field-live/voice/core/1ge4o24-i.opus",
  "/sparkpro-field-live/voice/core/1gfy05w-3.opus",
  "/sparkpro-field-live/voice/core/1gln1sx-5.opus",
  "/sparkpro-field-live/voice/core/1glolkd-j.opus",
  "/sparkpro-field-live/voice/core/1gqw4mf-1i.opus",
  "/sparkpro-field-live/voice/core/1gra621-3.opus",
  "/sparkpro-field-live/voice/core/1gs2yr6-b.opus",
  "/sparkpro-field-live/voice/core/1gxg0el-l.opus",
  "/sparkpro-field-live/voice/core/1gy1xfw-6.opus",
  "/sparkpro-field-live/voice/core/1h5h62q-1c.opus",
  "/sparkpro-field-live/voice/core/1h5z3kk-1g.opus",
  "/sparkpro-field-live/voice/core/1h6lmn1-a.opus",
  "/sparkpro-field-live/voice/core/1hahpju-n.opus",
  "/sparkpro-field-live/voice/core/1hi50y6-z.opus",
  "/sparkpro-field-live/voice/core/1hiumed-f.opus",
  "/sparkpro-field-live/voice/core/1hjocw2-15.opus",
  "/sparkpro-field-live/voice/core/1hpums4-h.opus",
  "/sparkpro-field-live/voice/core/1hthw4v-h.opus",
  "/sparkpro-field-live/voice/core/1htlq9q-6.opus",
  "/sparkpro-field-live/voice/core/1ib2lzu-18.opus",
  "/sparkpro-field-live/voice/core/1ic1tvr-b.opus",
  "/sparkpro-field-live/voice/core/1ick2s5-a.opus",
  "/sparkpro-field-live/voice/core/1iikebj-1r.opus",
  "/sparkpro-field-live/voice/core/1ikkigl-4.opus",
  "/sparkpro-field-live/voice/core/1ikpjjz-c.opus",
  "/sparkpro-field-live/voice/core/1il8srn-28.opus",
  "/sparkpro-field-live/voice/core/1imtn4h-9.opus",
  "/sparkpro-field-live/voice/core/1in098t-1j.opus",
  "/sparkpro-field-live/voice/core/1ivxxnv-7.opus",
  "/sparkpro-field-live/voice/core/1j28ios-m.opus",
  "/sparkpro-field-live/voice/core/1j2pvjf-a.opus",
  "/sparkpro-field-live/voice/core/1j7bs2r-p.opus",
  "/sparkpro-field-live/voice/core/1jox3u1-b.opus",
  "/sparkpro-field-live/voice/core/1jqcpv7-c.opus",
  "/sparkpro-field-live/voice/core/1jzm119-17.opus",
  "/sparkpro-field-live/voice/core/1k3lg2z-3.opus",
  "/sparkpro-field-live/voice/core/1ktye63-m.opus",
  "/sparkpro-field-live/voice/core/1kuzck9-1b.opus",
  "/sparkpro-field-live/voice/core/1l21yka-2y.opus",
  "/sparkpro-field-live/voice/core/1l3nhi0-m.opus",
  "/sparkpro-field-live/voice/core/1l6fgre-j.opus",
  "/sparkpro-field-live/voice/core/1l9igyb-m.opus",
  "/sparkpro-field-live/voice/core/1ldgg9e-4.opus",
  "/sparkpro-field-live/voice/core/1le1n0m-5.opus",
  "/sparkpro-field-live/voice/core/1llby0c-g.opus",
  "/sparkpro-field-live/voice/core/1lr3zu9-f.opus",
  "/sparkpro-field-live/voice/core/1lrtr2u-2h.opus",
  "/sparkpro-field-live/voice/core/1lwakzw-a.opus",
  "/sparkpro-field-live/voice/core/1lxg2ev-9.opus",
  "/sparkpro-field-live/voice/core/1lya1hk-9.opus",
  "/sparkpro-field-live/voice/core/1lzzsjc-18.opus",
  "/sparkpro-field-live/voice/core/1m84po3-g.opus",
  "/sparkpro-field-live/voice/core/1mpinvk-a.opus",
  "/sparkpro-field-live/voice/core/1n3dt9s-5.opus",
  "/sparkpro-field-live/voice/core/1ndahfg-b.opus",
  "/sparkpro-field-live/voice/core/1ne9eqd-p.opus",
  "/sparkpro-field-live/voice/core/1nfhvr5-d.opus",
  "/sparkpro-field-live/voice/core/1nh3gio-j.opus",
  "/sparkpro-field-live/voice/core/1ni1p7y-h.opus",
  "/sparkpro-field-live/voice/core/1ninj8e-1a.opus",
  "/sparkpro-field-live/voice/core/1nqf75f-1d.opus",
  "/sparkpro-field-live/voice/core/1nryiac-k.opus",
  "/sparkpro-field-live/voice/core/1nvpqbq-1b.opus",
  "/sparkpro-field-live/voice/core/1nwj2s3-m.opus",
  "/sparkpro-field-live/voice/core/1oehbaj-1d.opus",
  "/sparkpro-field-live/voice/core/1ois7xg-7.opus",
  "/sparkpro-field-live/voice/core/1orcj4x-8.opus",
  "/sparkpro-field-live/voice/core/1orpuct-10.opus",
  "/sparkpro-field-live/voice/core/1otp55x-d.opus",
  "/sparkpro-field-live/voice/core/1oxmgip-u.opus",
  "/sparkpro-field-live/voice/core/1p7d1fw-f.opus",
  "/sparkpro-field-live/voice/core/1pdr03e-a.opus",
  "/sparkpro-field-live/voice/core/1pjtvw8-d.opus",
  "/sparkpro-field-live/voice/core/1pop4u6-r.opus",
  "/sparkpro-field-live/voice/core/1pp35zj-a.opus",
  "/sparkpro-field-live/voice/core/1q0jm6t-f.opus",
  "/sparkpro-field-live/voice/core/1q6uksj-i.opus",
  "/sparkpro-field-live/voice/core/1qci6nd-9.opus",
  "/sparkpro-field-live/voice/core/1qei1ih-29.opus",
  "/sparkpro-field-live/voice/core/1qhtwh7-5.opus",
  "/sparkpro-field-live/voice/core/1qihzrb-g.opus",
  "/sparkpro-field-live/voice/core/1qpwior-5.opus",
  "/sparkpro-field-live/voice/core/1qqnn01-8.opus",
  "/sparkpro-field-live/voice/core/1qqtcdq-k.opus",
  "/sparkpro-field-live/voice/core/1qsb8wz-c.opus",
  "/sparkpro-field-live/voice/core/1r7g88q-i.opus",
  "/sparkpro-field-live/voice/core/1r9pchp-4.opus",
  "/sparkpro-field-live/voice/core/1rj8of6-b.opus",
  "/sparkpro-field-live/voice/core/1rkfp20-b.opus",
  "/sparkpro-field-live/voice/core/1rks22e-4.opus",
  "/sparkpro-field-live/voice/core/1rltpfy-j.opus",
  "/sparkpro-field-live/voice/core/1rn0zue-a.opus",
  "/sparkpro-field-live/voice/core/1rt2f7a-2g.opus",
  "/sparkpro-field-live/voice/core/1ruipgn-5.opus",
  "/sparkpro-field-live/voice/core/1rxaxeq-13.opus",
  "/sparkpro-field-live/voice/core/1s24xyr-8.opus",
  "/sparkpro-field-live/voice/core/1sfxt9d-j.opus",
  "/sparkpro-field-live/voice/core/1si1l1d-g.opus",
  "/sparkpro-field-live/voice/core/1snhpo8-j.opus",
  "/sparkpro-field-live/voice/core/1spdt0b-i.opus",
  "/sparkpro-field-live/voice/core/1ssmdg8-p.opus",
  "/sparkpro-field-live/voice/core/1sxah6r-b.opus",
  "/sparkpro-field-live/voice/core/1syvydv-24.opus",
  "/sparkpro-field-live/voice/core/1t1ywx0-2c.opus",
  "/sparkpro-field-live/voice/core/1t3zvc4-5.opus",
  "/sparkpro-field-live/voice/core/1t56u0t-c.opus",
  "/sparkpro-field-live/voice/core/1t69set-f.opus",
  "/sparkpro-field-live/voice/core/1t9yaj1-a.opus",
  "/sparkpro-field-live/voice/core/1ta6ugp-c.opus",
  "/sparkpro-field-live/voice/core/1tbuxl2-e.opus",
  "/sparkpro-field-live/voice/core/1tcn20n-1y.opus",
  "/sparkpro-field-live/voice/core/1teidtv-k.opus",
  "/sparkpro-field-live/voice/core/1thtvln-9.opus",
  "/sparkpro-field-live/voice/core/1tpbmgn-1c.opus",
  "/sparkpro-field-live/voice/core/1ttoid3-i.opus",
  "/sparkpro-field-live/voice/core/1tvh6nj-7.opus",
  "/sparkpro-field-live/voice/core/1u5fool-5.opus",
  "/sparkpro-field-live/voice/core/1u5vp8m-14.opus",
  "/sparkpro-field-live/voice/core/1u7tmco-f.opus",
  "/sparkpro-field-live/voice/core/1u8lxm0-1m.opus",
  "/sparkpro-field-live/voice/core/1uaooy8-2l.opus",
  "/sparkpro-field-live/voice/core/1uc7u2g-1o.opus",
  "/sparkpro-field-live/voice/core/1ucqrw9-9.opus",
  "/sparkpro-field-live/voice/core/1ud7vwt-b.opus",
  "/sparkpro-field-live/voice/core/1ufdvni-c.opus",
  "/sparkpro-field-live/voice/core/1ufmqbb-17.opus",
  "/sparkpro-field-live/voice/core/1usxh4w-b.opus",
  "/sparkpro-field-live/voice/core/1uw19t1-h.opus",
  "/sparkpro-field-live/voice/core/1uykdtr-a.opus",
  "/sparkpro-field-live/voice/core/1v1hlpy-j.opus",
  "/sparkpro-field-live/voice/core/1v37s97-a.opus",
  "/sparkpro-field-live/voice/core/1vc4oiv-b.opus",
  "/sparkpro-field-live/voice/core/1vfqfkv-t.opus",
  "/sparkpro-field-live/voice/core/1vicww2-d.opus",
  "/sparkpro-field-live/voice/core/1vm3a1j-c.opus",
  "/sparkpro-field-live/voice/core/1vtjnyd-m.opus",
  "/sparkpro-field-live/voice/core/1vv4y2p-r.opus",
  "/sparkpro-field-live/voice/core/1vvcet2-a.opus",
  "/sparkpro-field-live/voice/core/1vyybzm-m.opus",
  "/sparkpro-field-live/voice/core/1vzme8k-j.opus",
  "/sparkpro-field-live/voice/core/1w00akd-a.opus",
  "/sparkpro-field-live/voice/core/1w1b7hw-6.opus",
  "/sparkpro-field-live/voice/core/1w58i8e-1a.opus",
  "/sparkpro-field-live/voice/core/1w6q749-8.opus",
  "/sparkpro-field-live/voice/core/1w9lczq-j.opus",
  "/sparkpro-field-live/voice/core/1wa4p8b-c.opus",
  "/sparkpro-field-live/voice/core/1whcel1-f.opus",
  "/sparkpro-field-live/voice/core/1wly1qr-h.opus",
  "/sparkpro-field-live/voice/core/1wou3c7-1b.opus",
  "/sparkpro-field-live/voice/core/1wt7oqj-p.opus",
  "/sparkpro-field-live/voice/core/1wuu1py-17.opus",
  "/sparkpro-field-live/voice/core/1x2x2lq-l.opus",
  "/sparkpro-field-live/voice/core/1x5k49u-1f.opus",
  "/sparkpro-field-live/voice/core/1x7u0in-c.opus",
  "/sparkpro-field-live/voice/core/1xcnbw7-g.opus",
  "/sparkpro-field-live/voice/core/1xhwt8l-d.opus",
  "/sparkpro-field-live/voice/core/1xl5coo-2h.opus",
  "/sparkpro-field-live/voice/core/1xt7py2-w.opus",
  "/sparkpro-field-live/voice/core/1y724vz-9.opus",
  "/sparkpro-field-live/voice/core/1y8x86g-f.opus",
  "/sparkpro-field-live/voice/core/1yb9hss-s.opus",
  "/sparkpro-field-live/voice/core/1yc27fj-b.opus",
  "/sparkpro-field-live/voice/core/1ycr8my-7.opus",
  "/sparkpro-field-live/voice/core/1ytybpe-2l.opus",
  "/sparkpro-field-live/voice/core/1yxkzam-12.opus",
  "/sparkpro-field-live/voice/core/1yxlh7a-5.opus",
  "/sparkpro-field-live/voice/core/manifest.json"
]

// '/sparkpro-field-live/sw.js' → '/sparkpro-field-live/'
const BASE = self.location.pathname.replace(/sw\.js$/, '')

// Pull the shell and every hashed asset down on install, so the app opens
// offline even if its FIRST open is offline. Cached one-by-one on purpose:
// cache.addAll() rejects the whole batch if any single request fails, which
// would leave a tester with no cache at all because of one stale entry.
self.addEventListener('install', event => {
  event.waitUntil(
    caches.open(CACHE)
      .then(c => Promise.all(
        PRECACHE.map(url => c.add(url).catch(() => {}))
      ))
      .then(() => self.skipWaiting())
      .catch(() => self.skipWaiting())
  )
})

// Evict the SHELL caches this worker replaces — and nothing else.
//
// This used to delete every cache that was not the current one, which read as
// obviously correct and was catastrophic: the voice pack lives in a cache of
// its own (`sparkpro-voice-pro`, around 286 MB the tech chose to download over
// wifi), and the shell cache name is a hash of the asset list, so it changes on
// EVERY deploy. Each deploy therefore threw away the voice pack, and the next
// launch asked them to download it again — on cellular, in the field.
//
// It also destroyed exactly the thing the pack exists for. A tech who
// downloaded it deliberately so Spark would work with no signal would find it
// gone the first time they opened the app after any update.
//
// So the predicate is now explicit about what it owns. Anything that is not a
// SparkPro Field shell cache is somebody else's and is left alone; the app
// manages the voice packs itself and offers a Remove control for them.
const SHELL_PREFIX = 'sparkpro-field-'

self.addEventListener('activate', event => {
  event.waitUntil(
    caches.keys()
      .then(keys => Promise.all(
        keys
          .filter(k => k.startsWith(SHELL_PREFIX) && k !== CACHE)
          .map(k => caches.delete(k))
      ))
      .then(() => self.clients.claim())
  )
})

self.addEventListener('fetch', event => {
  const req = event.request
  if (req.method !== 'GET') return

  const url = new URL(req.url)

  // Cross-origin (Supabase, Google, model-lookup links) always goes to network.
  // Never serve a cached auth response.
  if (url.origin !== self.location.origin) return

  // Page loads: try network so a deployed update is picked up, but fall back to
  // the cached shell so the app still opens with no signal.
  if (req.mode === 'navigate') {
    event.respondWith(
      fetch(req)
        .then(res => {
          const copy = res.clone()
          caches.open(CACHE).then(c => c.put(req, copy)).catch(() => {})
          return res
        })
        .catch(() => caches.match(req).then(hit => hit || caches.match(BASE + 'index.html')))
    )
    return
  }

  // Static assets are content-hashed by Vite, so a cache hit is always correct
  // for that exact filename — cache-first is safe and makes cold opens instant.
  event.respondWith(
    caches.match(req).then(hit => {
      if (hit) return hit
      return fetch(req).then(res => {
        if (res.ok && res.type === 'basic') {
          const copy = res.clone()
          caches.open(CACHE).then(c => c.put(req, copy)).catch(() => {})
        }
        return res
      })
    })
  )
})
